# Generated by Django 2.1.5 on 2019-01-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190130_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_email',
            field=models.EmailField(default='goz@example.com', max_length=30, verbose_name='Yazar Email'),
            preserve_default=False,
        ),
    ]
